/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ödev2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author sunay
 */
public class Adres_Giris_ekran extends javax.swing.JFrame {

    public int enbuyuk = 0;

    public Adres_Giris_ekran() {
        initComponents();

        try {

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            Statement stmt = con.createStatement();
            String sql = "SELECT * FROM ADRES";
            ResultSet rs = stmt.executeQuery(sql);

            while (rs.next()) {
                if (rs.getInt("ADRES_ID") > enbuyuk) {
                    enbuyuk = rs.getInt("ADRES_ID");
                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(Adres_Giris_ekran.class.getName()).log(Level.SEVERE, null, ex);
        }

//        try {
//            // TODO add your handling code here:
//            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
//            Statement stmt = con.createStatement();
//            String sql_ıl = "SELECT * FROM IL";
//            ResultSet rs_ıl = stmt.executeQuery(sql_ıl);
//
//            while (rs_ıl.next()) {
//                String IL_ADI = rs_ıl.getString("IL_ADI");
//                jComboBox1.addItem(IL_ADI);
//            }
//            String sql_ıl_ıd = "SELECT * FROM IL WHERE IL_ADI='"+jComboBox1.getSelectedItem()+"'";
//            ResultSet rs_ıl_ıd = stmt.executeQuery(sql_ıl_ıd);
//            while (rs_ıl_ıd.next()) {
//                 a=rs_ıl_ıd.getInt("IL_ID");
//            }
//             String sql_ılce = "SELECT * FROM ILCE WHERE IL_ID="+a;
//            ResultSet rs_ılce = stmt.executeQuery(sql_ılce);
//            while (rs_ılce.next()) {                
//                String ılce_adı=rs_ılce.getString("ILCE_ADI");
//            
//            jComboBox2.addItem(ılce_adı);
//            }
//            
//        } catch (SQLException ex) {
//            Logger.getLogger(Kisi_Goster_Ekran.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * Creates new form adres_Giris_ekran
     */
    public String adı, soyadı;
    public int ıd;

    public Adres_Giris_ekran(int gelenID, String gelenADI, String gelenSOYADI) {

        initComponents();
        ıd = gelenID;
        adı = gelenADI;
        soyadı = gelenSOYADI;
        txt_kisiID.setText(ıd + "");
        int a = 0;
        try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            Statement stmt = con.createStatement();
            String sql_ıl = "SELECT * FROM IL";
            ResultSet rs_ıl = stmt.executeQuery(sql_ıl);

            while (rs_ıl.next()) {
                String IL_ADI = rs_ıl.getString("IL_ADI");
                jComboBox1.addItem(IL_ADI);
            }
//            String sql_ıl_ıd = "SELECT * FROM IL WHERE IL_ADI='"+jComboBox1.getSelectedItem()+"'";
//            ResultSet rs_ıl_ıd = stmt.executeQuery(sql_ıl_ıd);
//            if (rs_ıl_ıd.next()) {
//                 a=rs_ıl_ıd.getInt("IL_ID");
//            }
//             String sql_ılce = "SELECT * FROM ILCE WHERE IL_ID="+a;
//            ResultSet rs_ılce = stmt.executeQuery(sql_ılce);
//            while (rs_ılce.next()) {                
//                String ılce_adı=rs_ılce.getString("ILCE_ADI");
//                jComboBox2.addItem(ılce_adı);
//            }

        } catch (SQLException ex) {
            Logger.getLogger(Kisi_Goster_Ekran.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_no = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txt_kisiID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        txt_mahale = new javax.swing.JTextField();
        txt_sokak = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel7.setText("SOKAK:");

        jLabel8.setText("APT NO:");

        jLabel4.setText("İL:");

        jLabel5.setText("İLÇE:");

        jLabel6.setText("MAHALLE:");

        jButton1.setText("Adresleri göster");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Hepsini Ekle");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Hepsini Göster");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setText("Kişi ID:");

        jButton4.setText("Adres ekle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1İtemStateChanged(evt);
            }
        });
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txt_kisiID, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(32, 32, 32)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_mahale, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(19, 19, 19)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_sokak, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txt_kisiID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txt_mahale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txt_sokak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Adres_Göster_ekran().setVisible(true);
        jLabel2.setText("");
        jLabel3.setText("");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            String query = "INSERT INTO ADRES (ADRES_ID,IL,ILCE,MAHALLE,SOKAK,APR_NO,KISI_ID) VALUES (?,?,?,?,?,?,?)";
            PreparedStatement stm = con.prepareStatement(query);

            stm.setInt(1, enbuyuk + 1);
            stm.setString(2, jComboBox1.getSelectedItem().toString());
            stm.setString(3, jComboBox2.getSelectedItem().toString());
            stm.setString(4, txt_mahale.getText());
            stm.setString(5, txt_sokak.getText());
            stm.setInt(6, Integer.parseInt(txt_no.getText()));
            stm.setInt(7, Integer.parseInt(txt_kisiID.getText()));

            stm.executeUpdate();
            String query1 = "INSERT INTO PERSONEL (ID,ADI,SOYADI) VALUES (?,?,?)";
            PreparedStatement stm1 = con.prepareStatement(query1);

            stm1.setInt(1, ıd);
            stm1.setString(2, adı);
            stm1.setString(3, soyadı);

            stm1.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(Adres_Giris_ekran.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel2.setText("eklendi");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        new Adres_ve_Kişileri_Göster().setVisible(true);
        jLabel2.setText("");
        jLabel3.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            // TODO add your handling code here:
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            String query = "INSERT INTO ADRES (ADRES_ID,IL,ILCE,MAHALLE,SOKAK,APR_NO,KISI_ID) VALUES (?,?,?,?,?,?,?)";
            PreparedStatement stm = con.prepareStatement(query);

            stm.setInt(1, enbuyuk + 1);
            stm.setString(2, jComboBox1.getSelectedItem().toString());
            stm.setString(3, jComboBox2.getSelectedItem().toString());
            stm.setString(4, txt_mahale.getText());
            stm.setString(5, txt_sokak.getText());
            stm.setInt(6, Integer.parseInt(txt_no.getText()));
            stm.setInt(7, Integer.parseInt(txt_kisiID.getText()));

            stm.executeUpdate();
        } catch (SQLException ex) {
            Logger.getLogger(Adres_Giris_ekran.class.getName()).log(Level.SEVERE, null, ex);
        }
        jLabel3.setText("EKLENDİ");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1İtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1İtemStateChanged

        try {
            //         try {
//            // TODO add your handling code here:
//            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
//            Statement stmt = con.createStatement();
//            String sql = "SELECT * FROM IL";
//            ResultSet rs = stmt.executeQuery(sql);
//        
//            while (rs.next()) {
////                a1.ıd = rs.getInt("IL_ID");
//               String IL_ADI = rs.getString("IL_ADI");
////                a1.ilce = rs.getString("ILCE");
////                a1.mahalle = rs.getString("MAHALLE");
////                a1.sokak = rs.getString("SOKAK");
////                a1.no = rs.getInt("APR_NO");
// jComboBox1.addItem(IL_ADI);
//
//
//           
//            }
//        } catch (SQLException ex) {
//            Logger.getLogger(Kisi_Goster_Ekran.class.getName()).log(Level.SEVERE, null, ex);
//        }
            jComboBox2.removeAllItems();
            int a = 0;
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/sample", "app", "app");
            Statement stmt = con.createStatement();

            String sql_ıl_ıd = "SELECT * FROM IL WHERE IL_ADI='" + jComboBox1.getSelectedItem() + "'";
            ResultSet rs_ıl_ıd = stmt.executeQuery(sql_ıl_ıd);
            while (rs_ıl_ıd.next()) {
                a = rs_ıl_ıd.getInt("IL_ID");
            }
            String sql_ılce = "SELECT * FROM ILCE WHERE IL_ID=" + a;
            ResultSet rs_ılce = stmt.executeQuery(sql_ılce);
            while (rs_ılce.next()) {
                String ılce_adı = rs_ılce.getString("ILCE_ADI");
                jComboBox2.addItem(ılce_adı);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Adres_Giris_ekran.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jComboBox1İtemStateChanged

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed

    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adres_Giris_ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adres_Giris_ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adres_Giris_ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adres_Giris_ekran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adres_Giris_ekran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txt_kisiID;
    private javax.swing.JTextField txt_mahale;
    private javax.swing.JTextField txt_no;
    private javax.swing.JTextField txt_sokak;
    // End of variables declaration//GEN-END:variables
}
